---
openapi: 3.0.0
info:
  title: Records API
  description: This API receives records from users' devices
  contact:
    email: hmak28@my.bcit.ca
  version: 1.0.0
#servers:
#- url: https://virtserver.swaggerhub.com/Kloe/Records/1.0.0
#  description: SwaggerHub API Auto Mocking
tags:
- name: devices
  description: Operations available to users and trainers
paths:
  /readings/weight:
    get:
      tags:
        - devices
      summary: gets new weight readings
      operationId: app.get_weight_readings
      description: Gets weight readings added after a timestamp
      parameters:
        - name: timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of weight events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeightReading'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /readings/calories:
    get:
      tags:
        - devices
      summary: gets new calories readings
      operationId: app.get_calories_readings
      description: Gets calories readings added after a timestamp
      parameters:
        - name: timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of calories events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaloriesReading'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    WeightReading:
      required:
      - timestamp
      - user_id
      - user_name
      - weight
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        user_name:
          type: string
          example: Tom Chong
        weight:
          type: integer
          example: 60
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
    CaloriesReading:
      required:
      - calories
      - timestamp
      - user_id
      - user_name
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        user_name:
          type: string
          example: Tom Chong
        calories:
          type: integer
          example: 2000
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
